### ISSUE TITLE
Crash under Linux when selecting a level

### ISSUE THREAD

**Issue by ghost** [Tricky1975/BallPlayCupid#77]
This happens on Linux with 16.5.1.beta. Selecting a level to play crashes the game.
Here's the backtrace:

```
Loading game
Error: LIBS/SAVE.LLL/SAVE.LUA:78: save.load('SCRIPT/GAME.LLL/PUZZLES/PZ01.lua',nil,nil): attempt to call a nil value
stack traceback:
    [C]: in function 'error'
    LIBS/SAVE.LLL/SAVE.LUA:78: in function 'load'
    SCRIPT/PICKMAINPUZZLE.LUA:103: in function <SCRIPT/PICKMAINPUZZLE.LUA:94>
    SCRIPT/PICKMAINPUZZLE.LUA:114: in function 'mousepressed'
    LIBS/CHAIN.LLL/CHAIN.LUA:75: in function <LIBS/CHAIN.LLL/CHAIN.LUA:72>
    [string "boot.lua"]:454: in function <[string "boot.lua"]:435>
    [C]: in function 'xpcall'
```

**Comment by ghost** [comment]
Renaming `PZ01.LUA` in the directory `SCRIPT/GAME.LLL/PUZZLES/` to `PZ01.lua` (only `lua` in lower case) fixed it for that level and I could proceed to the game screen. Now on to actually check the game! ;)

**Comment by Tricky1975** [comment]
Now this is really serious. Anyway, this will be an easy fix, so I will get to this once I've taken a shower (I'm just out of bed... It's morning in my timezone) :)
