### ISSUE TITLE
Highlight the level under the mouse in the level selector

### ISSUE THREAD

**Issue by ghost** [Tricky1975/BallPlayCupid#78]
This is a feature request. To help see what the player is supposed to do when in the level selection screen, it would be nice if the currently "hot" element (the one that would be selected if the user clicked) was highlighted in some way.

**Comment by Tricky1975** [comment]
This should already happen. Maybe the difference in color was not well visible on your monitor. I can try to make the difference a little bigger so you can see it ;)

**Comment by ghost** [comment]
Oops, you're right, I didn't notice. The green one is quite obvious, but the red one is barely noticeable.

**Comment by Tricky1975** [comment]
Well, that should be easy then. Just a little adjustment in the color scale should fix this ;)

**Comment by Tricky1975** [comment]
I've made the color for unhighlighted text in the red mode a bit darker, as the range between the unhighlighed and highlighted text was just too small. Now the visuality is better.
This change will take effect once the stable version has been released which is (for now) planned halfway in June.
